- block:
  - name: 判断 firewalld 是否安装
    shell: >
      systemctl status firewalld | grep active || echo "not be found"
    register: firewalld_already_installed
  
  - name: 禁用防火墙
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: '"active" in firewalld_already_installed.stdout'
  when: "(firewalld_disabled | bool) | default(true)"

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 安装依赖
  yum:
    name: 
    - gcc
    - make
    state: latest

- include_tasks: common.yml

- name: 生成 redis-server service 配置
  template:
    src: redis.service.j2
    dest: /usr/lib/systemd/system/redis.service

- name: 生成 redis-sentinel service 配置
  template:
    src: redis-sentinel.service.j2
    dest: /usr/lib/systemd/system/redis-sentinel.service