- block:
  - name: 判断 ufw 是否安装
    shell: >
      systemctl status ufw | grep active || echo "not be found"
    register: ufw_already_installed
  
  - name: 禁用防火墙
    service:
      name: ufw
      state: stopped
      enabled: no
    when: '"active" in ufw_already_installed.stdout'
  when: "(firewalld_disabled | bool) | default(true)"

- name: 安装依赖
  apt: 
    name:
    - gcc
    - make
    state: present
    allow_unauthenticated: true

- include_tasks: common.yml

- name: 生成 redis-server service 配置
  template:
    src: redis.service.j2
    dest: /lib/systemd/system/redis.service

- name: 生成 redis-sentinel service 配置
  template:
    src: redis-sentinel.service.j2
    dest: /lib/systemd/system/redis-sentinel.service