- name: 安装依赖
  apt: 
    name:
    - gcc
    - make
    state: present
    allow_unauthenticated: true

- include_tasks: common.yml

- name: 生成 redis-server service 配置
  template:
    src: redis.service.j2
    dest: /lib/systemd/system/redis.service

- name: 生成 redis-sentinel service 配置
  template:
    src: redis-sentinel.service.j2
    dest: /lib/systemd/system/redis-sentinel.service