# 提权操作
ansible_become: true
command_warnings: false
firewalld_disabled: true

# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"

# master节点IP
MYSQL_MASTER_IP: >-
  {%- if groups['mysql'].index(inventory_hostname)|int == 0 -%}
  {%- if hostvars[inventory_hostname]['ansible_host'] is defined -%}
  {{ hostvars[groups['mysql'][groups['mysql']|length|int - 1]]['ansible_host'] }}
  {%- else -%}
  {{ groups['mysql'][groups['mysql']|length|int - 1] }}
  {%- endif -%}
  {%- else -%}
  {%- if hostvars[inventory_hostname]['ansible_host'] is defined -%}
  {{ hostvars[groups['mysql'][groups['mysql'].index(inventory_hostname)|int - 1]]['ansible_host'] }}
  {%- else -%}
  {{ groups['mysql'][groups['mysql'].index(inventory_hostname)|int - 1] }}
  {%- endif -%}
  {%- endif -%}

_host_architecture_groups:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
host_architecture: >-
  {%- if ansible_architecture in _host_architecture_groups -%}
  {{ _host_architecture_groups[ansible_architecture] }}
  {%- else -%}
  {{ ansible_architecture }}
  {%- endif -%}

_host_distribution_groups:
  uos: debian
host_distribution: >-
  {%- if ansible_distribution in _host_distribution_groups -%}
  {{ _host_distribution_groups[ansible_distribution] }}
  {%- else -%}
  {{ ansible_distribution }}
  {%- endif -%}

host_distribution_release: >-
  {%- if (ansible_distribution_release == 'n/a') or (ansible_distribution_release is not defined) or (ansible_distribution_release == '') -%}
  buster
  {%- else -%}
  {{ ansible_distribution_release }}
  {%- endif -%}

# keepalived auth_type 的 password
lb_keepalived_password: "Ch0erodon"
# 区分多个 instance 的 VRRP 组播，同网段不能重复，取值在0-255之间
lb_keepalived_router_id: 51
# 默认所有节点权重 120
LB_KEEPALIVED_PRIORITY: "120"
# 节点初始主备状态
LB_KEEPALIVED_STATE: "{% if inventory_hostname == groups['mysql'][0] %}MASTER{% else %}BACKUP{% endif %}"

# Centos repo
mysql_connectors_community_yum_repo: http://repo.mysql.com/yum/mysql-connectors-community/el/7/$basearch/
mysql_tools_community_yum_repo: http://repo.mysql.com/yum/mysql-tools-community/el/7/$basearch/
mysql_community_yum_repo: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/

# Ubuntu repo
mysql_community_apt_repo: deb http://mirrors.ustc.edu.cn/mysql-repo/apt/{{ host_distribution | lower }} {{ host_distribution_release }} mysql-5.7 mysql-tools

auth:
  # root用户密码
  rootPassword: Changeit!123
  # 创建一个mysql用户（选填）
  replicationUser: replicator
  replicationPassword: Changeit!123

# MySQL 配置
mysqld:
  datadir: /var/lib/mysql
  port: 3306
  bind_address: 0.0.0.0
  skip_name_resolve: 1
  lower_case_table_names: 1
  max_allowed_packet: 1073741824
  max_connections: 2500
  max_connect_errors: 500
  table_open_cache: 2000
  character_set_server: utf8mb4
  collation_server: utf8mb4_general_ci