- hosts: 
  - mysql
  tasks:
  - name: 重启 keepalived
    service:
      name: keepalived
      state: restarted
      enabled: yes
    when: "groups['redis']|length > 1"

  - name: 重启 mysql
    service:
      name: mysql
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]

  - name: 重启 mysql
    service:
      name: mysqld
      state: restarted
      enabled: yes
      when: ansible_distribution in [ 'CentOS','OracleLinux','RedHat' ]
