- hosts: 
  - mysql
  tasks:
  - name: 停止 keepalived
    service:
      name: keepalived
      state: stop
      enabled: yes
    when: "groups['redis']|length > 1"

  - name: 停止 mysql
    service:
      name: mysql
      state: stop
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]

  - name: 停止 mysql
    service:
      name: mysqld
      state: stop
      enabled: yes
      when: ansible_distribution in [ 'CentOS','OracleLinux','RedHat' ]

  - name: 删除 mysql 相关文件或目录
    file: 
      name: "{{ item }}"
      state: absent
    with_items:
      - "/etc/my.cnf.d/mysqld.cnf"
      - "/etc/mysql/mysql.conf.d/mysqld.cnf"
      - "/etc/keepalived/keepalived.conf"
      - "{{ mysqld.datadir }}"
