- hosts: 
  - mysql
  tasks:
  - name: 重启 keepalived
    service:
      name: keepalived
      state: restarted
      enabled: yes
    when: "groups['redis']|length > 1"

  - name: 重启 mysql
    service:
      name: mysql
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]

  - name: 重启 mysql
    service:
      name: mysqld
      state: restarted
      enabled: yes
      when: ansible_distribution in [ 'CentOS','OracleLinux','RedHat' ]

  - shell: pgrep mysql
    register: pgrep_mysql_out
    name: get mysql pid
  
  - name: show mysql pid
    debug:
      var: pgrep_mysql_out.stdout