- hosts: 
  - redis
  tasks:
  - name: 停止 redis
    service:
      name: redis
      state: stopped
      enabled: yes

  - name: 启动 redis
    service:
      name: redis
      state: started
      enabled: yes

  - block:
    - name: 停止 redis-sentinel
      service:
        name: redis-sentinel
        state: stopped
        enabled: yes

    - name: 启动 redis-sentinel
      service:
        name: redis-sentinel
        state: started
        enabled: yes
    when: "groups['redis']|length > 1"

    - shell: pgrep redis-server
      register: pgrep_redis_server_out
      name: get redis-server pid
    
    - shell: pgrep redis-sentinel
      register: pgrep_redis_sentinel_out
      name: get redis-sentinel pid
    
    - name: show redis pid
      debug:
        var: pgrep_redis_server_out.stdout
      
    - name: show redis-sentinel pid
      debug:
        var: pgrep_redis_sentinel_out.stdout