- name: 重新启动 cron 避免因修改时区而导致的作业错乱问题
  service:
    name: cron
    state: restarted
    enabled: yes

- name: 安装 chrony
  apt: 
    name:
    - chrony
    state: present
    allow_unauthenticated: true

- name: 配置 chrony server
  template: 
    src: server.conf.j2 
    dest: /etc/chrony/chrony.conf
  when: inventory_hostname == groups['chrony'][0]

- name: 配置 chrony client
  template: 
    src: client.conf.j2 
    dest: /etc/chrony/chrony.conf
  when: inventory_hostname != groups['chrony'][0]

- name: 启动 chrony 
  service: 
    name: chrony
    state: restarted 
    enabled: yes