- name: 判断 ntp 是否早已安装
  shell: >
    systemctl status ntp | grep running || echo "not running"
  register: ntp_already_running

- name: 停止系统原有 ntp
  when: '"active" in ntp_already_running.stdout'
  service:
    name: ntp
    state: stopped
    enabled: no

- name: "统一时区为 {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- include_tasks: centos.yml
  when: ansible_distribution in [ 'CentOS','OracleLinux','RedHat' ]

- include_tasks: debian.yml
  when: ansible_distribution in [ 'Ubuntu','Debian' ]
